// Build tool: compiles src/render/inject_shaders.h with Microsoft's
// d3dcompiler_47.dll (SM5.1 DXBC) and writes src/render/inject_shaders_bin.h,
// so the mod doesn't depend on a shader compiler at run time (Proton's
// d3dcompiler can't build these shaders).
//
//   tools/compile_shaders.sh [path to d3dcompiler_47.dll]   (Linux, via Wine)
//   compile_shaders.exe <out header>                        (Windows)
#include <windows.h>

#include <d3dcompiler.h>

#include <cstdint>
#include <cstdio>
#include <cstring>
#include <string>

#include "../src/render/inject_shaders.h"

namespace {
uint64_t Fnv1a(const char* s) {
    uint64_t h = 1469598103934665603ull;
    for (; *s; ++s) {
        h ^= uint8_t(*s);
        h *= 1099511628211ull;
    }
    return h;
}
} // namespace

int main(int argc, char** argv) {
    if (argc < 2) {
        std::fprintf(stderr, "usage: compile_shaders <out header>\n");
        return 2;
    }
    HMODULE comp = LoadLibraryW(L"d3dcompiler_47.dll");
    auto compile = comp ? reinterpret_cast<decltype(&D3DCompile)>(reinterpret_cast<void*>(GetProcAddress(comp, "D3DCompile")))
                        : nullptr;
    if (!compile) {
        std::fprintf(stderr, "d3dcompiler_47.dll / D3DCompile not found\n");
        return 2;
    }
    struct Job {
        const char* entry;
        const char* target;
        const char* name;
    } jobs[] = {{"VSGBuffer", "vs_5_1", "kVSGBuffer"},
                {"PSGBuffer", "ps_5_1", "kPSGBuffer"},
                {"VSShadow", "vs_5_1", "kVSShadow"},
                {"PSShadow", "ps_5_1", "kPSShadow"},
                {"PSShadowCut", "ps_5_1", "kPSShadowCut"},
                {"CSReduceDepth", "cs_5_1", "kCSReduceDepth"}};
    std::string out;
    char line[128];
    std::snprintf(line, sizeof(line), "0x%016llxull", static_cast<unsigned long long>(Fnv1a(sm2m::kInjectShaderSource)));
    out += "// Generated by tools/compile_shaders from src/render/inject_shaders.h with\n";
    out += "// Microsoft d3dcompiler_47 (SM5.1 DXBC). Do not edit; rerun the tool instead.\n";
    out += "#pragma once\n\n#include <cstdint>\n\nnamespace sm2m::shaderbin {\n\n";
    out += std::string("// FNV-1a of kInjectShaderSource these blobs were built from.\n") +
           "constexpr uint64_t kSourceHash = " + line + ";\n\n";
    for (const Job& j : jobs) {
        ID3DBlob* code = nullptr;
        ID3DBlob* err = nullptr;
        const HRESULT hr = compile(sm2m::kInjectShaderSource, std::strlen(sm2m::kInjectShaderSource), "inject_shaders.h",
                                   nullptr, nullptr, j.entry, j.target, D3DCOMPILE_OPTIMIZATION_LEVEL3, 0, &code, &err);
        if (FAILED(hr) || !code) {
            std::fprintf(stderr, "%s: %s\n", j.entry, err ? static_cast<const char*>(err->GetBufferPointer()) : "failed");
            return 1;
        }
        const uint8_t* p = static_cast<const uint8_t*>(code->GetBufferPointer());
        const size_t n = code->GetBufferSize();
        out += std::string("alignas(4) inline const unsigned char ") + j.name + "[] = {";
        for (size_t i = 0; i < n; ++i) {
            if (i % 20 == 0) out += "\n   ";
            std::snprintf(line, sizeof(line), " %u,", unsigned(p[i]));
            out += line;
        }
        out += "\n};\n\n";
        std::printf("%-14s %s %zu bytes\n", j.entry, j.target, n);
        code->Release();
        if (err) err->Release();
    }
    out += "} // namespace sm2m::shaderbin\n";
    FILE* f = std::fopen(argv[1], "wb");
    if (!f) {
        std::fprintf(stderr, "can't write %s\n", argv[1]);
        return 1;
    }
    std::fwrite(out.data(), 1, out.size(), f);
    std::fclose(f);
    return 0;
}
